export const defaultThemeVariables = {
  color: {
    orange: '#FF8440',
    orangeDark: '#E86825',
    orangePale: '#FFE1BE',
    black: '#000',
    blackLighter: '#1C1C23',
    white: '#fff',
    grey: '#9F9C99',
    greyDark: '#7f7b77',
    greyLight: '#EEE',
    greyLightSecondary: '#C4C4C4',
    greyLighter: '#BFBDBC',
    beigePale: '#F9F7F3',
    beigePaleLight: '#F3EFE8',
    beigePaleDark: '#D6D2CE',
    greyBlueLight: '#f8f9fa',
    green: '#008556',
    greenPale: '#D6F3E2',
    red: '#de1c22',
  },
  fontSizeGlobal: {
    regular: 16,
    xxl: 15,
    xl: 14,
  },
  fontSize: {
    bigTitle: 32,
    regularTitle: 24,
    bigger: 22,
    big: 20,
    regularBig: 18,
    regular: 16,
    middle: 14,
    small: 12,
  },
  margins: {
    small: 10,
    base: 20,
    big: 40,
  },
  fontWeight: {
    regular: 400,
    medium: 500,
    bold: 700,
  },
  border: {
    smallest: 1,
    smaller: 2,
    small: 4,
    big: 6,
  },
  borderRadius: {
    regular: 0,
    big: 50,
    small: 8,
    smaller: 4,
  },
  zIndex: {
    zIndexLowest: -30,
    zIndexLower: -20,
    zIndexLow: -10,
    zIndexDefault: 'auto',
    zIndexHigh: 10,
    zIndexHigher: 20,
    zIndexHighest: 30,
  },
  padding: {
    container: {
      big: 20,
      base: 16,
      small: 12,
      smaller: 8,
      min: 4,
    },
    innerOffset: {
      base: 20,
      small: 8,
    },
  },
}
